CREATE TABLE CLIENTS
(
  ID_CLIENT integer PRIMARY KEY NOT NULL IDENTITY,
  NAME varchar(30) NOT NULL,
  SURNAME varchar(30) NOT NULL,
  PATRONOMIC varchar(30),
  PHONE varchar(30) NOT NULL
);
CREATE UNIQUE INDEX CLIENTS_ID_CLIENT_UINDEX ON CLIENTS (ID_CLIENT);
CREATE UNIQUE INDEX CLIENTS_PHONE_UINDEX ON CLIENTS (PHONE);

CREATE TABLE MECHANICS
(
  ID_MECHANIC integer PRIMARY KEY NOT NULL IDENTITY,
  NAME varchar(30) NOT NULL,
  SURNAME varchar(30),
  PATRONOMIC varchar(30),
  HOURLYPAYMENT double NOT NULL
);
CREATE UNIQUE INDEX MECHANICS_ID_MECHANIC_UINDEX ON MECHANICS (ID_MECHANIC);

CREATE TABLE ORDERS
(
  ID_ORDER integer PRIMARY KEY NOT NULL IDENTITY,
  ID_CLIENT integer NOT NULL,
  ID_MECHANIC integer NOT NULL,
  DATE_OF_CREATION timestamp NOT NULL,
  END_DATE timestamp NOT NULL,
  COST float NOT NULL,
  ID_STATUS integer NOT NULL,
  DESCRIPTION varchar(300) NOT NULL,
  CONSTRAINT ORDERS_CLIENTS_ID_CLIENT_FK FOREIGN KEY (ID_CLIENT) REFERENCES CLIENTS (ID_CLIENT),
  CONSTRAINT ORDERS_MECHANICS_ID_MECHANIC_FK FOREIGN KEY (ID_MECHANIC) REFERENCES MECHANICS (ID_MECHANIC),
  CONSTRAINT ORDERS_STATUSES_ID_STATUS_FK FOREIGN KEY (ID_STATUS) REFERENCES STATUSES (ID_STATUS)
);
CREATE UNIQUE INDEX ORDERS_ID_ORDER_UINDEX ON ORDERS (ID_ORDER);

CREATE TABLE STATUSES
(
  ID_STATUS integer PRIMARY KEY NOT NULL,
  STATUS varchar(30) NOT NULL
);
CREATE UNIQUE INDEX STATUSES_STATUS_UINDEX ON STATUSES (STATUS);
CREATE UNIQUE INDEX STATUSES_ID_STATUS_UINDEX ON STATUSES (ID_STATUS);

INSERT INTO CLIENTS (NAME, SURNAME, PATRONOMIC, PHONE) VALUES ('Иван', 'Федоров', 'Алексеевич', '83542234582');
INSERT INTO CLIENTS (NAME, SURNAME, PATRONOMIC, PHONE) VALUES ('Алексей', 'Сидоров', 'Петрович', '87834567432');
INSERT INTO CLIENTS (NAME, SURNAME, PATRONOMIC, PHONE) VALUES ('Андрей', 'Савельев', 'Владимирович', '89823456743');
INSERT INTO CLIENTS (NAME, SURNAME, PATRONOMIC, PHONE) VALUES ('Роман', 'Ефимов', 'Романович', '89653438212');
INSERT INTO MECHANICS (NAME, SURNAME, PATRONOMIC, HOURLYPAYMENT) VALUES ('Виталий', 'Шишкин', 'Иванович', 500);
INSERT INTO MECHANICS (NAME, SURNAME, PATRONOMIC, HOURLYPAYMENT) VALUES ('Владислав', 'Матвеев', 'Игоревич', 700);
INSERT INTO STATUSES (ID_STATUS, STATUS) VALUES (1, 'Scheduled');
INSERT INTO STATUSES (ID_STATUS, STATUS) VALUES (2, 'Completed');
INSERT INTO STATUSES (ID_STATUS, STATUS) VALUES (3, 'Accepted');
INSERT INTO ORDERS (ID_CLIENT, ID_MECHANIC, DATE_OF_CREATION, END_DATE, COST, ID_STATUS, DESCRIPTION) VALUES (0, 0, '2017-06-30 18:31:22', '2017-07-01 18:31:46', 1000, 1, 'Диагностика' );
INSERT INTO ORDERS (ID_CLIENT, ID_MECHANIC, DATE_OF_CREATION, END_DATE, COST, ID_STATUS, DESCRIPTION) VALUES (1, 0, '2017-06-30 18:31:36', '2017-07-23 18:31:58', 5000, 1, 'Ремонт Подвески');
INSERT INTO ORDERS (ID_CLIENT, ID_MECHANIC, DATE_OF_CREATION, END_DATE, COST, ID_STATUS, DESCRIPTION) VALUES (2, 1, '2017-06-25 18:31:40', '2017-06-27 18:32:01', 3000, 2, 'Шиномонтаж');
INSERT INTO ORDERS (ID_CLIENT, ID_MECHANIC, DATE_OF_CREATION, END_DATE, COST, ID_STATUS, DESCRIPTION) VALUES (3, 1, '2017-03-30 18:31:44', '2017-05-26 18:32:04', 1000, 3, 'Регулировка фар');